"""Requirements.txt 构建器 — 生成精简、版本锁定的依赖文件。"""

import subprocess
import sys
from pathlib import Path
from typing import Dict, List, Optional, Set


def build_minimal_requirements(
    matched_packages: Set[str],
    freeze_data: Dict[str, str],
    missing_packages: List[str],
    pin_versions: bool = True,
) -> str:
    """Generate a minimal requirements.txt from matched + missing packages.

    Args:
        matched_packages: Set of PyPI package names declared AND used.
        freeze_data: {package: version} from pip freeze (or requirements.txt).
        missing_packages: Packages that are used but not declared.
        pin_versions: Whether to pin exact versions.

    Returns:
        A string containing the generated requirements.txt content.
    """
    lines: List[str] = []
    lines.append("# Generated by import-guard")
    lines.append("# Minimal dependencies based on actual code imports")
    lines.append("")

    all_packages = sorted(matched_packages) + sorted(missing_packages)

    for pkg in all_packages:
        version = freeze_data.get(pkg)
        if pin_versions and version:
            lines.append(f"{pkg}=={version}")
        else:
            lines.append(pkg)

    if lines[-1] != "":
        lines.append("")
    return "\n".join(lines)


def generate_with_pip_compile(
    matched_packages: Set[str],
    output_path: str = "requirements-minimal.txt",
) -> Optional[str]:
    """Use pip-compile (pip-tools) to generate a fully resolved requirements.txt.

    This is the most reliable approach: produce a .in file with only the
    packages you need, then let pip-compile resolve all transitive deps.
    """
    in_path = output_path.replace(".txt", ".in.txt")

    with open(in_path, "w") as f:
        f.write("# Minimal dependency list — auto-generated by import-guard\n")
        for pkg in sorted(matched_packages):
            f.write(f"{pkg}\n")

    try:
        subprocess.run(
            [sys.executable, "-m", "piptools", "compile", in_path, "-o", output_path],
            check=True,
            capture_output=True,
            text=True,
        )
        return output_path
    except (subprocess.CalledProcessError, FileNotFoundError):
        # pip-tools not installed, fall through
        return None


def write_requirements(
    content: str,
    output_path: str = "requirements-minimal.txt",
) -> None:
    """Write the generated requirements content to a file."""
    Path(output_path).write_text(content, encoding="utf-8")


def diff_requirements(
    old_path: str,
    new_path: str,
) -> Dict[str, int]:
    """Compare old vs new requirements.txt and return stats.

    Returns:
        {"added": N, "removed": N, "kept": N}
    """
    from ..scanner.import_parser import parse_requirements_txt

    old = parse_requirements_txt(old_path)
    new = parse_requirements_txt(new_path)

    return {
        "added": len(new - old),
        "removed": len(old - new),
        "kept": len(old & new),
    }
