"""HTML 报告生成器 — 生成可读的 HTML 审计报告。"""

import webbrowser
from pathlib import Path
from typing import Set

from ..analyzer.diff_engine import DiffResult
from ..analyzer.unused_detector import UnusedReport
from ..analyzer.missing_detector import MissingReport

HTML_TEMPLATE = """<!DOCTYPE html>
<html lang="zh-CN">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<title>Import Guard — Dependency Audit Report</title>
<style>
  body {{ font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', Roboto, sans-serif;
         max-width: 960px; margin: 0 auto; padding: 24px; background: #f8f9fa; color: #212529; }}
  h1 {{ border-bottom: 2px solid #dee2e6; padding-bottom: 12px; }}
  h2 {{ margin-top: 32px; }}
  .summary-cards {{ display: flex; gap: 16px; flex-wrap: wrap; }}
  .card {{ flex: 1; min-width: 180px; padding: 16px; border-radius: 8px; text-align: center; }}
  .card.matched {{ background: #d4edda; border: 1px solid #c3e6cb; }}
  .card.unused {{ background: #f8d7da; border: 1px solid #f5c6cb; }}
  .card.missing {{ background: #fff3cd; border: 1px solid #ffeaa7; }}
  .card .number {{ font-size: 2em; font-weight: bold; }}
  .card .label {{ color: #6c757d; font-size: 0.9em; }}
  table {{ width: 100%; border-collapse: collapse; margin-top: 12px; }}
  th, td {{ padding: 8px 12px; text-align: left; border-bottom: 1px solid #dee2e6; }}
  th {{ background: #e9ecef; }}
  .unused-row td {{ color: #dc3545; }}
  .missing-row td {{ color: #e6a817; }}
  .footer {{ margin-top: 40px; font-size: 0.85em; color: #adb5bd; text-align: center; }}
  .savings {{ background: #d4edda; border: 1px solid #c3e6cb; border-radius: 6px;
              padding: 12px 16px; margin-top: 16px; }}
</style>
</head>
<body>

<h1>📦 Import Guard — Dependency Audit Report</h1>

<div class="summary-cards">
  <div class="card matched">
    <div class="number">{matched}</div>
    <div class="label">Matched (declared + used)</div>
  </div>
  <div class="card unused">
    <div class="number">{unused}</div>
    <div class="label">Unused (declared, not used)</div>
  </div>
  <div class="card missing">
    <div class="number">{missing}</div>
    <div class="label">Missing (used, not declared)</div>
  </div>
</div>

{savings_section}

<h2>🚫 Unused Dependencies</h2>
{unused_table}

<h2>⚠️ Missing Dependencies</h2>
{missing_table}

<h2>✅ Matched Dependencies</h2>
{matched_section}

<div class="footer">
  Generated by <strong>import-guard</strong> — dependency auditor for Python projects
</div>

</body>
</html>
"""


def _build_savings_html(est_mb: float, est_sec: float) -> str:
    if est_mb <= 0:
        return ""
    return f"""
<div class="savings">
  <strong>💡 Potential Savings:</strong>
  {est_mb:.1f} MB disk space &middot; ~{est_sec:.1f}s install time
</div>"""


def _build_unused_table(report: UnusedReport) -> str:
    if not report.packages:
        return "<p>✅ No unused dependencies found.</p>"
    rows = []
    for p in report.packages:
        size_str = f"{p.size_bytes / 1024:.1f} KB" if p.size_bytes else "?"
        ver = p.version or "?"
        rows.append(
            f'<tr class="unused-row">'
            f'<td>{p.name}</td><td>{ver}</td><td>{size_str}</td>'
            f'</tr>'
        )
    return (
        '<table><tr><th>Package</th><th>Version</th><th>Size</th></tr>'
        + "".join(rows)
        + "</table>"
    )


def _build_missing_table(report: MissingReport) -> str:
    if not report.packages:
        return "<p>✅ No missing dependencies — all imports are declared.</p>"
    rows = []
    for p in report.packages:
        rows.append(
            f'<tr class="missing-row">'
            f'<td>{p.import_name}</td><td>{p.package_name}</td>'
            f'<td><code>{p.suggested_spec}</code></td>'
            f'</tr>'
        )
    return (
        '<table><tr><th>Import Name</th><th>Package</th><th>Suggested Spec</th></tr>'
        + "".join(rows)
        + "</table>"
    )


def _build_matched_section(matched: Set[str]) -> str:
    if not matched:
        return "<p>No matched dependencies.</p>"
    items = "".join(f"<li>{pkg}</li>" for pkg in sorted(matched))
    return f"<ul>{items}</ul>"


def generate_html(
    diff: DiffResult,
    unused_report: UnusedReport,
    missing_report: MissingReport,
) -> str:
    """Generate a full HTML report string."""
    savings = _build_savings_html(
        unused_report.estimated_savings_mb,
        unused_report.estimated_time_saved_seconds,
    )
    return HTML_TEMPLATE.format(
        matched=len(diff.matched),
        unused=unused_report.total_count,
        missing=missing_report.total_count,
        savings_section=savings,
        unused_table=_build_unused_table(unused_report),
        missing_table=_build_missing_table(missing_report),
        matched_section=_build_matched_section(diff.matched),
    )


def write_html_report(
    diff: DiffResult,
    unused_report: UnusedReport,
    missing_report: MissingReport,
    output_path: str,
    open_browser: bool = False,
) -> None:
    """Write HTML report to a file, optionally opening in browser."""
    html = generate_html(diff, unused_report, missing_report)
    path = Path(output_path)
    path.write_text(html, encoding="utf-8")
    if open_browser:
        webbrowser.open(f"file://{path.resolve()}")
